PROMPT ELIMINANDO TABLESPACE dx_tallerc;
DROP TABLESPACE dx_tallerc INCLUDING CONTENTS AND DATAFILES;
PROMPT ELIMINANDO TABLESPACE ix_tallerc;
DROP TABLESPACE ix_tallerc INCLUDING CONTENTS AND DATAFILES;
PROMPT ELIMINANDO USUARIO tallerc;
DROP USER tallerc CASCADE;