PROMPT CREANDO FK_PAIS_DEPARTAMENTO TABLA tallerc.Departamento ;
ALTER TABLE tallerc.Departamento ADD CONSTRAINT FK_PAIS_DEPARTAMENTO FOREIGN KEY (idPais) REFERENCES tallerc.Pais (id);
ALTER TABLE tallerc.Ciudad ADD CONSTRAINT FK_PAIS_DEPARTAMENTO FOREIGN KEY (idDepartamento) REFERENCES tallerc.Departamento (id);