PROMPT CREANDO PK_ID_PAIS;
ALTER TABLE tallerc.Pais ADD CONSTRAINT PK_ID_PAIS PRIMARY KEY (id);
ALTER TABLE tallerc.Departamento ADD CONSTRAINT PK_ID_DEPARTAMENTO PRIMARY KEY (id);
ALTER TABLE tallerc.Ciudad ADD CONSTRAINT PK_ID_CIUDAD PRIMARY KEY (id);
